name: TaskMenT CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: task-progress
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d task-progress"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://postgres:password@localhost:5432/task-progress
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_ACCESS_TOKEN_EXPIRES_IN: ${{ secrets.JWT_ACCESS_TOKEN_EXPIRES_IN }}
      FE_URL: ${{ secrets.FE_URL }}

    defaults:
      run:
        working-directory: tm-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: tm-backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Lint
        run: npm run lint

      - name: Apply database migrations
        run: npx prisma migrate deploy

      - name: Run unit tests
        run: npm run test

      - name: Run end-to-end tests
        run: npm run test:e2e

      - name: Build
        run: npm run build

  # frontend:
  #   runs-on: ubuntu-latest

  #   defaults:
  #     run:
  #       working-directory: tm-frontend

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 22
  #         cache: npm
  #         cache-dependency-path: tm-frontend/package-lock.json

  #     - name: install dependencies
  #       run: npm ci

  #     - name: Run Lint
  #       run: npm run lint

  #     - name: Run build
  #       run: npm run build
